resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: pr-open
    type: pull-request
    icon: github
    check_every: 1m
    source:
      repository: https://github.com/ONSdigital/baw-client-rest
      access_token: ((shared-github.access_token))
      base_branch: main
      disable_forks: true
      states: ["OPEN"]
      required_review_approvals: 0


# resources:
# - name: baw-client-rest
#   type: git
#   icon: github-circle
#   source:
#     uri: https://github.com/ONSdigital/baw-client-rest
#     branch: ((branch))
#     username: ((github.access_token))
#     password: x-oauth-basic

jobs:
# - name: lint
#   plan:
#   - get: baw-client-rest
#     trigger: true
#   - task: lint
#     file: baw-client-rest/ci/tasks/lint.yml

- name: unit-test
  plan:
    - do:
      - get: pr-open
          trigger: true
          version: every
      - put: pr-open
        params:
          path: pr-open
          status: pending
          context: unit-testing
      - task: unit-test
        file: baw-client-rest/ci/tasks/test.yml
  on_success:
    put: pr-open
    params:
      path: pr-open
      status: success
      context: static-testing
  on_failure:
    put: pr-open
    params:
      path: pr-open
      status: failure
      context: static-testing