resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: pr-open
    type: pull-request
    icon: github
    check_every: 1m
    source:
      repository: ONSdigital/baw-client-rest
      access_token: ((github.access_token))
      base_branch: main
      disable_forks: true
      states: ["OPEN"]
      required_review_approvals: 0

jobs:
- name: linting
  serial: true
  plan:
    - do:
      - get: pr-open
        trigger: true
        version: every
      - put: pr-open
        params:
          path: pr-open
          status: pending
          context: linting
      - task: linting
        input_mapping: {baw-client-rest: pr-open}
        file: pr-open/ci/tasks/lint.yml
  on_success:
    put: pr-open
    params:
      path: pr-open
      status: success
      context: linting
  on_failure:
    put: pr-open
    params:
      path: pr-open
      status: failure
      context: linting

- name: unit-test
  serial: true
  plan:
    - do:
      - get: pr-open
        trigger: true
        version: every
      - put: pr-open
        params:
          path: pr-open
          status: pending
          context: unit-testing
      - task: unit-test
        input_mapping: {baw-client-rest: pr-open}
        file: pr-open/ci/tasks/test.yml
  on_success:
    put: pr-open
    params:
      path: pr-open
      status: success
      context: unit-testing
  on_failure:
    put: pr-open
    params:
      path: pr-open
      status: failure
      context: unit-testing